[build]
  publish = "dist"

[[redirects]]
  from = "/upload"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/upload/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
